### ISSUE TITLE
Add scoping

### ISSUE THREAD

**Issue by stam** [CodeYellowBV/chimera-cub#2]
Allow a frontend to further narrow its subscription.

**Comment by SpaceK33z** [comment]
Preferably this would be compatible with query parameters as much as possible (don't know if you already had that in mind). That would make it possible for the frontend to do a GET request + subscribe to a socket with the same parameters.

**Comment by abzainuddin** [comment]
This is done by using more specific rooms. The creation of rooms is pretty cheap.
