### ISSUE TITLE
Prevent exception when trying to setup connection while being unauthenticated 

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/chimera-cub#5]
In this line:
https://github.com/CodeYellowBV/high-templar/blob/master/high_templar/connection.py#L28

You can see that the code assumes the `user` object always exists as bootstrap response (`GET /api/bootstrap` on backend). However, when you're not logged in, it's `user: null`.

I understand that you should not connect to the websocket server while being unauthenticated, but still it should show a human error.

**Comment by sjamaan** [comment]
I just fixed that with 3a50e8168e1eca05b56db59a33e2308584836b58.

@stam Could you give me access to publish a new release on pypi? My username there is `sjamaan`.

**Comment by sjamaan** [comment]
@stam I just noticed that the release on pypi is 2.1.1, but I just tagged my fix as 2.1.1 because the tag for 2.1.1 was missing. plz fix :)

**Comment by stam** [comment]
@sjamaan I added you as maintainer!

**Comment by sjamaan** [comment]
Thanks! This bug is fixed with 2.1.2 :)
